name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Instalar dependencias
        run: npm install

      - name: Construir imagen Docker
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/my-node-app:latest .

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Subir imagen a Docker Hub
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/my-node-app:latest